src/FrontendSchemeRegistration.UI/ViewModels/SubsidiaryCheckDetailsViewModel.cs
using System.Diagnostics.CodeAnalysis;

namespace FrontendSchemeRegistration.UI.ViewModels;

[ExcludeFromCodeCoverage]
public class SubsidiaryCheckDetailsViewModel
{
    public string CompanyName { get; set; }

    public string CompaniesHouseNumber { get; set; }

    public AddressViewModel? BusinessAddress { get; set; }

    public bool? IsCompanyAlreadyLinkedToTheParent { get; set; }

    public string? ParentCompanyName { get; set; }

    public string? ParentCompanyCompaniesHouseNumber { get; set; }

    public bool? IsCompanyAlreadyLinkedToOtherParent { get; set; }

    public string? OtherParentCompanyName { get; set; }    
}

src/FrontendSchemeRegistration.UI/Controllers/LandingController.cs
namespace FrontendSchemeRegistration.UI.Controllers;

using Application.Services.Interfaces;
using Constants;
using ControllerExtensions;
using Extensions;
using FrontendSchemeRegistration;
using Microsoft.AspNetCore.Mvc;

[Route("/")]
public class LandingController : Controller
{
    private readonly IComplianceSchemeService _complianceSchemeService;

    public LandingController(IComplianceSchemeService complianceSchemeService)
    {
        _complianceSchemeService = complianceSchemeService;
    }

    [HttpGet]
    public async Task<IActionResult> Get()
    {
        var userData = User.GetUserData();
        var organisation = userData.Organisations[0];

        if (organisation.OrganisationRole == OrganisationRoles.ComplianceScheme)
        {
            return RedirectToAction(
                nameof(ComplianceSchemeLandingController.Get),
                nameof(ComplianceSchemeLandingController).RemoveControllerFromName());
        }

        var producerComplianceScheme = await _complianceSchemeService.GetProducerComplianceScheme(organisation.Id.Value);

        if (producerComplianceScheme is not null)
        {
            return RedirectToAction(
                nameof(ComplianceSchemeMemberLandingController.Get),
                nameof(ComplianceSchemeMemberLandingController).RemoveControllerFromName());
        }

        return RedirectToAction(
            nameof(FrontendSchemeRegistrationController.VisitHomePageSelfManaged),
            nameof(FrontendSchemeRegistrationController).RemoveControllerFromName());
    }
}

src/FrontendSchemeRegistration.UI/Controllers/SubsidiaryCheckDetailsController.cs
using EPR.Common.Authorization.Constants;
using EPR.Common.Authorization.Sessions;
using FrontendSchemeRegistration.Application.Constants;
using FrontendSchemeRegistration.Application.DTOs.Subsidiary;
using FrontendSchemeRegistration.Application.Services.Interfaces;
using FrontendSchemeRegistration.UI.Extensions;
using FrontendSchemeRegistration.UI.Sessions;
using FrontendSchemeRegistration.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FrontendSchemeRegistration.UI.Controllers;

[Authorize(Policy = PolicyConstants.EprFileUploadPolicy)]
[Route(PagePaths.SubsidiaryCheckDetails)]
public class SubsidiaryCheckDetailsController : Controller
{
    private readonly ISessionManager<FrontendSchemeRegistrationSession> _sessionManager;
    private readonly ISubsidiaryService _subsidiaryService;

    public SubsidiaryCheckDetailsController(
        ISessionManager<FrontendSchemeRegistrationSession> sessionManager,
        ISubsidiaryService subsidiaryService)
    {
        _sessionManager = sessionManager;
        _subsidiaryService = subsidiaryService;
    }

    [HttpGet]
    public async Task<IActionResult> Get()
    {
        var session = await _sessionManager.GetSessionAsync(HttpContext.Session);

        if (session?.SubsidiarySession?.Company == null)
        {
            return RedirectToAction("Get", "SubsidiaryCompaniesHouseNumber");
        }

        var viewModel = new SubsidiaryCheckDetailsViewModel()
        {
            CompanyName = session.SubsidiarySession.Company.Name,
            CompaniesHouseNumber = session.SubsidiarySession.Company.CompaniesHouseNumber,
            BusinessAddress = new AddressViewModel
            {
                AddressSingleLine = session.SubsidiarySession.Company.BusinessAddress?.AddressSingleLine,
                Street = session.SubsidiarySession.Company.BusinessAddress?.Street,
                Town = session.SubsidiarySession.Company.BusinessAddress?.Town,
                County = session.SubsidiarySession.Company.BusinessAddress?.County,
                Country = session.SubsidiarySession.UkNation?.ToString(),
                Postcode = session.SubsidiarySession.Company.BusinessAddress?.Postcode
            },

            IsCompanyAlreadyLinkedToTheParent = session.SubsidiarySession.Company?.IsCompanyAlreadyLinkedToTheParent,
            IsCompanyAlreadyLinkedToOtherParent = session.SubsidiarySession.Company?.IsCompanyAlreadyLinkedToOtherParent,
            ParentCompanyName = session.UserData.Organisations?.FirstOrDefault()?.Name,
            ParentCompanyCompaniesHouseNumber = session.UserData.Organisations?.FirstOrDefault()?.CompaniesHouseNumber,
            OtherParentCompanyName = session.SubsidiarySession.Company?.OtherParentCompanyName,
        };

        ViewBag.BackLinkToDisplay = Url.Content($"~{PagePaths.SubsidiaryLocation}");

        return View("SubsidiaryCheckDetails", viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Post(SubsidiaryCheckDetailsViewModel model)
    {
        ViewBag.BackLinkToDisplay = Url.Content($"~{PagePaths.SubsidiaryLocation}");

        if (!ModelState.IsValid)
        {
            return View("SubsidiaryCheckDetails", model);
        }

        var session = await _sessionManager.GetSessionAsync(HttpContext.Session);

        if (session?.SubsidiarySession?.Company == null)
        {
            return RedirectToAction("Get", "SubsidiaryCompaniesHouseNumber");
        }

        var userOrganisation = User.GetUserData().Organisations.FirstOrDefault();

        var subsidiary = session.SubsidiarySession.Company;

        if ((subsidiary?.IsCompanyAlreadyLinkedToOtherParent == true) && !string.IsNullOrEmpty(subsidiary.OtherParentCompanyName))
        {
            var newReferenceNumber = await _subsidiaryService.AddSubsidiary(new SubsidiaryAddDto 
            {
                ChildOrganisationId = Guid.Parse(subsidiary.OrganisationId),
                ParentOrganisationId = userOrganisation?.Id
            });

            _sessionManager.UpdateSessionAsync(HttpContext.Session, x => x.SubsidiarySession.Company.OrganisationId = newReferenceNumber);
        }
        else
        {
            var newReferenceNumber = await _subsidiaryService.SaveSubsidiary(new SubsidiaryDto
            {
                Subsidiary = new OrganisationModel
                {
                    OrganisationType = OrganisationType.NotSet,
                    ProducerType = ProducerType.NotSet,
                    CompaniesHouseNumber = subsidiary?.CompaniesHouseNumber,
                    Name = subsidiary?.Name,
                    Address = new AddressModel
                    {
                        SubBuildingName = subsidiary?.BusinessAddress?.SubBuildingName,
                        BuildingName = subsidiary?.BusinessAddress?.BuildingName,
                        BuildingNumber = subsidiary?.BusinessAddress?.BuildingNumber,
                        Street = subsidiary?.BusinessAddress?.Street,
                        Locality = subsidiary?.BusinessAddress?.Locality,
                        DependentLocality = subsidiary?.BusinessAddress?.DependentLocality,
                        Town = subsidiary?.BusinessAddress?.Town,
                        County = subsidiary?.BusinessAddress?.County,
                        Postcode = subsidiary?.BusinessAddress?.Postcode,
                        Country = subsidiary?.BusinessAddress?.Country
                    },
                    IsCompanyAlreadyLinkedToOtherParent = subsidiary?.IsCompanyAlreadyLinkedToOtherParent,
                    OtherParentCompanyName = subsidiary?.OtherParentCompanyName,
                    ValidatedWithCompaniesHouse = true,
                    IsComplianceScheme = false,
                    Nation = session.SubsidiarySession.UkNation
                },
                ParentOrganisationId = userOrganisation?.Id
            });

            _sessionManager.UpdateSessionAsync(HttpContext.Session, x => x.SubsidiarySession.Company.OrganisationId = newReferenceNumber);
        }

        return RedirectToAction("Get", "SubsidiaryAdded");
    }
}

src/FrontendSchemeRegistration.UI/Views/SubsidiaryCheckDetails/SubsidiaryCheckDetails.cshtml
@model SubsidiaryCheckDetailsViewModel

@{
    ViewData["Title"] = Localizer["report-packaging-data"];
}
@await Html.PartialAsync("Partials/Govuk/_AccountActionBar")
<main class="govuk-main-wrapper govuk-!-padding-top-4" id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
            @using (Html.BeginForm("Get", "Landing", null, FormMethod.Get))
            {
                <div class="govuk-form-group">
                    <h1 class="govuk-heading-l govuk-!-margin-top-4 govuk-!-margin-bottom-7">
                        @Localizer["check-details"]
                    </h1>
                </div>
            }
            @using (Html.BeginForm("Post", "SubsidiaryCheckDetails", Model))
            {
                <dl class="govuk-summary-list">
                    <h2 class="govuk-heading-m">@Localizer["producer-details-heading"]</h2>

                    <div class="govuk-summary-list__row govuk-!-font-weight-bold">
                        <dt class="govuk-summary-list__key">
                            @Localizer["producer-name"]
                        </dt>
                        <dd class="govuk-summary-list__value govuk-!-font-weight-bold">
                            @Model.ParentCompanyName
                        </dd>
                    </div>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            @Localizer["companies-house-number"]
                        </dt>
                        <dd class="govuk-summary-list__value">
                            @Model.ParentCompanyCompaniesHouseNumber
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <a class="govuk-link govuk-link--no-visited-state" asp-controller="SubsidiaryCompaniesHouseNumber" asp-action="Get"
                               asp-route-submissionId="">@SharedLocalizer["change"]</a><span class="govuk-visually-hidden"> @Localizer["companies-house-number"]</span>
                        </dd>
                    </div>
                    <h2 class="govuk-heading-m govuk-!-margin-top-9">@Localizer["subsidiary-details-heading"]</h2>

                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key govuk-!-font-weight-bold">
                            @Localizer["companies-house-number"]
                        </dt>
                        <dd class="govuk-summary-list__value">
                            @Model.CompaniesHouseNumber
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <a class="govuk-link govuk-link--no-visited-state" asp-controller="SubsidiaryCompaniesHouseNumber" asp-action="Get"
                               asp-route-submissionId="">@SharedLocalizer["change"]</a><span class="govuk-visually-hidden"> @Localizer["companies-house-number"]</span>
                        </dd>
                    </div>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            @Localizer["organisation-details"]
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <div>
                                @{
                                    RenderCompanyParts(new[] { Model.CompanyName });
                                    RenderAddressParts(Model.BusinessAddress?.AddressFields);
                                }
                            </div>
                        </dd>
                    </div>                   
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            @Localizer["uk-nation"]
                        </dt>
                        <dd class="govuk-summary-list__value">
                            @Model.BusinessAddress.Country
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <ul class="govuk-summary-list__actions-list">
                                <a class="govuk-link govuk-link--no-visited-state" asp-controller="SubsidiaryLocation" asp-action="Get">@SharedLocalizer["change"]</a>
                                <span class="govuk-visually-hidden"> @Localizer["uk-nation"]</span>
                            </ul>
                        </dd>
                    </div>
                </dl>

                <h1 class="govuk-heading-l">@Localizer["declaration"]</h1>
                <p class="govuk-body">@Localizer["declaration_statement"]</p>

                <div class="govuk-warning-text">
                    <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
                    <strong class="govuk-warning-text__text">
                        <span class="govuk-warning-text__assistive">@Localizer["text_assistive.warning"]</span>
                        @Localizer["declaration_warning"]
                    </strong>
                </div>
                <button class="govuk-button" data-module="govuk-button">@SharedLocalizer["confirm_and_continue"]</button>
            }
        </div>
    </div>
</main>

@{

    void RenderCompanyParts(string?[] addressParts)
    {
        if (addressParts is not null)
        {
            foreach (string part in addressParts.Where(p => !string.IsNullOrWhiteSpace(p)))
            {
                <div><b>@part</b></div>
            }
        }
    }

    void RenderAddressParts(string?[] addressParts)
    {
        if (addressParts is not null)
        {
            foreach (string part in addressParts.Where(p => !string.IsNullOrWhiteSpace(p)))
            {
                <div>@part</div>
            }
        }
    }
}