src/FrontendSchemeRegistration.UI/Controllers/Prns/PrnsRejectController.cs
using FrontendSchemeRegistration.Application.Constants;
using FrontendSchemeRegistration.UI.Attributes.ActionFilters;
using FrontendSchemeRegistration.UI.Constants;
using FrontendSchemeRegistration.UI.Controllers.ControllerExtensions;
using FrontendSchemeRegistration.UI.Services.Interfaces;
using FrontendSchemeRegistration.UI.ViewModels.Prns;
using Microsoft.AspNetCore.Mvc;
using Microsoft.FeatureManagement.Mvc;

namespace FrontendSchemeRegistration.UI.Controllers.Prns
{
    [FeatureGate(FeatureFlags.ShowPrn)]
    [ServiceFilter(typeof(ComplianceSchemeIdHttpContextFilterAttribute))]
    public class PrnsRejectController : Controller
    {
        private readonly IPrnService _prnService;
        private readonly IDownloadPrnService _downloadPrnService;

        public PrnsRejectController(IPrnService prnService, IDownloadPrnService downloadPrnService)
        {
            _prnService = prnService;
            _downloadPrnService = downloadPrnService;
        }

        // Reject single Prn. Step 3 of 5, are you sure?
        [HttpGet]
        [Route(PagePaths.Prns.AskToReject + "/{id:guid}")]
        public async Task<IActionResult> RejectSinglePrn(Guid id)
        {
            var prn = await _prnService.GetPrnByExternalIdAsync(id);

            return View("RejectSinglePrn", prn);
        }

        // Unexpected hit, assume user has timed out and been redirected here after relogin
        [HttpGet]
        [Route(PagePaths.Prns.ConfirmReject)]
        public async Task<ActionResult> ConfirmRejectSinglePrnPassThrough()
        {
            return RedirectToAction(nameof(PrnsController.SelectMultiplePrns), nameof(PrnsController).RemoveControllerFromName());
        }

        // Reject single Prn. Step 4 of 5 update PRN to rejected
        [HttpPost]
        [Route(PagePaths.Prns.ConfirmReject)]
        public async Task<ActionResult> ConfirmRejectSinglePrnPassThrough(PrnViewModel model)
        {
            await _prnService.RejectPrnAsync(model.ExternalId);

            return RedirectToAction(nameof(PrnsRejectController.RejectedPrn), nameof(PrnsRejectController).RemoveControllerFromName(), new { id = model.ExternalId });
        }

        // Reject single Prn. Step 5 of 5 show updated PRN details following rejection
        [HttpGet]
        [Route(PagePaths.Prns.Rejected + "/{id:guid}")]
        public async Task<IActionResult> RejectedPrn(Guid id)
        {
            var model = await _prnService.GetPrnByExternalIdAsync(id);

            if (model == null || !model.ApprovalStatus.Equals(PrnStatus.Rejected))
            {
                return RedirectToAction(nameof(PrnsObligationController.ObligationsHome), nameof(PrnsObligationController).RemoveControllerFromName());
            }

            return View(model);
        }

        [HttpGet]
        [Route(PagePaths.Prns.DownloadRejectedPRNPdf + "/{id:guid}")]
        public async Task<IActionResult> DownloadPrn(Guid id)
        {
            var actionContext = new ActionContext(HttpContext, RouteData, ControllerContext.ActionDescriptor, ModelState);
            return await _downloadPrnService.DownloadPrnAsync(id, "RejectedPrn", actionContext);
        }
    }
}

src/FrontendSchemeRegistration.UI/Views/PrnsReject/RejectSinglePrn.cshtml
@using FrontendSchemeRegistration.UI.Controllers.Prns
@using FrontendSchemeRegistration.UI.ViewModels.Prns
@model PrnViewModel

@{
    ViewData["Title"] = Localizer[(Model.IsPrn ? "page_title_prn" : "page_title_pern")];
}
<main class="govuk-main-wrapper govuk-!-padding-top-4" id="confirm-rject-prn">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">

            <form class="form" method="POST">
                @Html.HiddenFor(model => model.ExternalId)
                <h2 class="govuk-heading-l">@Localizer[(Model.IsPrn ? "reject_this_prn" : "reject_this_pern")]</h2>

                <p class="govuk-body-m">@Localizer["this_is_permanent_and_cannot_be_undone"]</p>

                <div class="govuk-button-group">
                    @if (Model.IsStatusEditable)
                    {
                        <button class="govuk-button" type="submit" asp-action=@nameof(PrnsRejectController.ConfirmRejectSinglePrnPassThrough) asp-controller="PrnsReject">
                            @Localizer["yes_reject"]
                        </button>
                    }

                    @Html.ActionLink(@Localizer["no_go_back"].Value, nameof(PrnsController.SelectSinglePrn), "Prns",
                        new
                        {
                            id = @Model.ExternalId
                        },
                        new
                        {
                            @class = "govuk-button govuk-button--secondary"
                        })
                </div>
            </form>
        </div>
    </div>
</main>

src/FrontendSchemeRegistration.UI/Views/PrnsReject/RejectedPrn.cshtml
@using FrontendSchemeRegistration.UI.Controllers.Prns
@using FrontendSchemeRegistration.UI.ViewModels.Prns
@inject IStringLocalizer<PrnDataResources> PrnDataLocalizer
@model PrnViewModel

@{
    ViewData["Title"] = Localizer["page_title"];
    var isPdf = ViewData["IsPdf"] as bool? ?? false;
}
<main class="govuk-main-wrapper govuk-!-padding-top-4" id="main-content" role="main">

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
            @await Html.PartialAsync("../Shared/Partials/Prns/_agenciesLogo.cshtml")
            @if (!isPdf)
            {
                <div class="govuk-notification-banner govuk-notification-banner--success" role="alert" aria-labelledby="govuk-notification-banner-title" data-module="govuk-notification-banner">
                    <div class="govuk-notification-banner__header">
                        <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
                            @SharedLocalizer["success"]
                        </h2>
                    </div>

                    <div class="govuk-notification-banner__content">
                        <h3 class="govuk-notification-banner__heading">
                            @string.Format(Localizer["prn_rejected"].Value, PrnDataLocalizer[Model.NoteType])
                        </h3>
                    </div>
                </div>
            }

            <h1 class="govuk-heading-l">
                @Localizer[(Model.IsPrn ? "prn_note" : "pern_note")]
            </h1>
            <div class="govuk-inset-text app-inset-text">
                <div class="govuk-heading-m">
                    @string.Format(Localizer["prn_number"].Value, PrnDataLocalizer[Model.NoteType]): <strong>@Model.PrnOrPernNumber</strong>
                </div>
                <div class="govuk-heading-m">
                    @Localizer["year"]: <strong>@Model.IssueYear</strong>
                </div>
            </div>

            @await Html.PartialAsync("../Shared/Partials/Prns/_recyclingNoteStatus.cshtml", Model)
            <br>
            @await Html.PartialAsync("../Shared/Partials/Prns/_recyclingNoteDetails.cshtml", Model)
            <br>
            <br>
            @if (!isPdf)
            {
                <div class="govuk-button-group">
                        @Html.ActionLink(string.Format(Localizer["accept_or_reject_more_prns_and_perns"].Value, PrnDataLocalizer[PrnConstants.PrnsText], PrnDataLocalizer[PrnConstants.PernsText]),
                                nameof(PrnsController.SelectMultiplePrns), "Prns", null,
                                new
                                {
                                    @class = "govuk-button"
                                })

                    <button id="downloadPDFButton" class="govuk-button govuk-button--secondary">
                        @string.Format(Localizer["download_this_prn"].Value, PrnDataLocalizer[Model.NoteType])
                    </button>
                </div>
                <p class="govuk-body">
                    @Html.ActionLink(Localizer["manage_obligation_home"].Value, nameof(PrnsObligationController.ObligationsHome), "PrnsObligation",
                             null,
                             new
                             {
                                 @class = "govuk-link govuk-link--no-visited-state"
                             })
                </p>
            }
        </div>
    </div>
</main>
@section Scripts {
    <script src="~/js/html2pdf-0.9.3.min.js"></script>
    <script src="~/js/download-pdf.js"></script>
}