src/FrontendSchemeRegistration.UI/Controllers/Prns/PrnsAcceptController.cs
using EPR.Common.Authorization.Sessions;
using FrontendSchemeRegistration.Application.Constants;
using FrontendSchemeRegistration.UI.Attributes.ActionFilters;
using FrontendSchemeRegistration.UI.Constants;
using FrontendSchemeRegistration.UI.Controllers.ControllerExtensions;
using FrontendSchemeRegistration.UI.Services.Interfaces;
using FrontendSchemeRegistration.UI.Sessions;
using FrontendSchemeRegistration.UI.ViewModels.Prns;
using Microsoft.AspNetCore.Mvc;
using Microsoft.FeatureManagement.Mvc;

namespace FrontendSchemeRegistration.UI.Controllers.Prns
{
    [FeatureGate(FeatureFlags.ShowPrn)]
    [ServiceFilter(typeof(ComplianceSchemeIdHttpContextFilterAttribute))]
    public class PrnsAcceptController : Controller
    {
        private readonly IPrnService _prnService;
        private readonly ISessionManager<FrontendSchemeRegistrationSession> _sessionManager;
        private const string NoPrnsSelected = "NoPrnsSelected";
        private readonly IDownloadPrnService _downloadPrnService;

        public PrnsAcceptController(IPrnService prnService, ISessionManager<FrontendSchemeRegistrationSession> sessionManager,
            IDownloadPrnService downloadPrnService)
        {
            _prnService = prnService;
            _sessionManager = sessionManager;
            _downloadPrnService = downloadPrnService; 
        }

        // Note steps 1 and 2 are in the PrnsController
        // Accept single Prn. Step 3 of 5, are you sure?
        [HttpGet]
        [Route(PagePaths.Prns.AskToAccept + "/{id:guid}")]
        public async Task<IActionResult> AcceptSinglePrn(Guid id)
        {
            var prn = await _prnService.GetPrnByExternalIdAsync(id);
            
            return View("AcceptSinglePrn", prn);
        }        

        // Unexpected hit, assume user has timed out and been redirected here after relogin
        [HttpGet]
        [Route(PagePaths.Prns.ConfirmAccept)]
        public async Task<ActionResult> ConfirmAcceptSinglePrnPassThrough()
        {
            return RedirectToAction(nameof(PrnsController.SelectMultiplePrns), nameof(PrnsController).RemoveControllerFromName());
        }

        // Accept single Prn. Step 4 of 5, update PRN to accpted
        [HttpPost]
        [Route(PagePaths.Prns.ConfirmAccept)]
        public async Task<ActionResult> ConfirmAcceptSinglePrnPassThrough(PrnViewModel model)
        {
            await _prnService.AcceptPrnAsync(model.ExternalId);

            return RedirectToAction(nameof(PrnsAcceptController.AcceptedPrn), nameof(PrnsAcceptController).RemoveControllerFromName(), new { id = model.ExternalId });
        }

        // Accept single Prn. Step 5 of 5, show updated PRN details following acceptance
        [HttpGet]
        [Route(PagePaths.Prns.Accepted + "/{id:guid}")]
        public async Task<IActionResult> AcceptedPrn(Guid id)
        {
            var model = await _prnService.GetPrnByExternalIdAsync(id);

            if (model == null || !model.ApprovalStatus.EndsWith(PrnStatus.Accepted))
            {
                return RedirectToAction(nameof(PrnsObligationController.ObligationsHome), nameof(PrnsObligationController).RemoveControllerFromName());
            }

            return View(model);
        }

        [HttpGet]
        [Route(PagePaths.Prns.DownloadAcceptedPRNPdf + "/{id:guid}")]
        public async Task<IActionResult> DownloadPrn(Guid id)
        {
            var actionContext = new ActionContext(HttpContext, RouteData, ControllerContext.ActionDescriptor, ModelState);
            return await _downloadPrnService.DownloadPrnAsync(id, "AcceptedPrn", actionContext);
        }

        // Note step 1 is in the PrnsController
        // Unexpected hit, assume user has timed out and been redirected here after relogin
        [HttpGet]
        [Route(PagePaths.Prns.BeforeAskToAcceptMany)]
        public async Task<ActionResult> AcceptMultiplePrnsPassThrough()
        {
            return RedirectToAction(nameof(PrnsController.SelectMultiplePrns), nameof(PrnsController).RemoveControllerFromName());
        }

        // Accept multiple Prns. Step 2 of 5 remember chosen PRN ids
        [HttpPost]
        [Route(PagePaths.Prns.BeforeAskToAcceptMany)]
        public async Task<ActionResult> AcceptMultiplePrnsPassThrough(PrnListViewModel model)
        {
            var selectedPrns = model.Prns.Where(x => x.IsSelected)
                            .Concat(model.PreviousSelectedPrns.Where(x => x.IsSelected))
                            .DistinctBy(x => x.ExternalId).ToList();

            if (selectedPrns.Count != 0)
            {
                var session = await _sessionManager.GetSessionAsync(HttpContext.Session) ?? new FrontendSchemeRegistrationSession();
                session.PrnSession = new PrnSession();
                session.PrnSession.SelectedPrnIds = selectedPrns.Select(x => x.ExternalId).ToList();
                session.PrnSession.InitialNoteTypes = model.GetPluralNoteType(selectedPrns);
                await _sessionManager.SaveSessionAsync(HttpContext.Session, session);

                return RedirectToAction(nameof(PrnsAcceptController.AcceptMultiplePrns));
            }
            TempData[NoPrnsSelected] = "select_one_or_more_prns_or_perns_to_accept_them";
            return RedirectToAction(nameof(PrnsController.SelectMultiplePrns), nameof(PrnsController).RemoveControllerFromName(), 
            new SearchPrnsViewModel()
            {
                FilterBy = model.FilterBy, SortBy = model.SortBy  
            });
        }

        // Accept multiple Prns. Step 3 of 5 display chosen PRNs with option to deselect
        [HttpGet]
        [Route(PagePaths.Prns.AskToAcceptMany + "/{id?}")]
        public async Task<ActionResult> AcceptMultiplePrns(Guid id)
        {
            var session = await _sessionManager.GetSessionAsync(HttpContext.Session) ?? new FrontendSchemeRegistrationSession();
            List<Guid> selectedPrnIds = session.PrnSession.SelectedPrnIds;
            ViewBag.StartNoteTypes = session.PrnSession.InitialNoteTypes;
            PrnListViewModel viewModel = await _prnService.GetPrnsAwaitingAcceptanceAsync();

            if (id != Guid.Empty)
            {
                var removedPrn = viewModel.Prns.First(x => x.ExternalId == id);
                viewModel.RemovedPrn = new RemovedPrn(removedPrn.PrnOrPernNumber, removedPrn.IsPrn);
                
                selectedPrnIds.Remove(id);         
                session.PrnSession.SelectedPrnIds = selectedPrnIds.ToList();
                await _sessionManager.SaveSessionAsync(HttpContext.Session, session);
            }

            var selectedPrns = viewModel?.Prns?.Where(x => selectedPrnIds.Contains(x.ExternalId)).OrderBy(x => x.Material).ThenByDescending(x => x.DateIssued);
            if (selectedPrns != null)
            {
                viewModel.Prns = selectedPrns.ToList();
            }
            
            ViewBag.BackLinkToDisplay = Url.Content($"~/{PagePaths.Prns.ShowAwaitingAcceptance}");
            
            return View(viewModel);
        }

        // Unexpected hit, assume user has timed out and been redirected here after relogin
        [HttpGet]
        [Route(PagePaths.Prns.ConfirmAcceptMany)]
        public async Task<ActionResult> ConfirmAcceptMultiplePrnsPassThrough()
        {
            return RedirectToAction(nameof(PrnsController.SelectMultiplePrns), nameof(PrnsController).RemoveControllerFromName());
        }

        // Accept multiple Prns. Step 4 of 5 update PRNs to accpted
        [HttpPost]
        [Route(PagePaths.Prns.ConfirmAcceptMany)]
        public async Task<ActionResult> ConfirmAcceptMultiplePrnsPassThrough(PrnListViewModel model)
        {
            var selectedPrnIds = model.Prns.Select(x => x.ExternalId);
            await _prnService.AcceptPrnsAsync(selectedPrnIds.ToArray());
            return RedirectToAction(nameof(PrnsAcceptController.AcceptedPrns));
        }

        // Accept multiple Prns. Step 5 of 5 display newly accepted PRN summary details
        [HttpGet]
        [Route(PagePaths.Prns.AcceptedMany)]
        public async Task<IActionResult> AcceptedPrns()
        {
            var session = await _sessionManager.GetSessionAsync(HttpContext.Session) ?? new FrontendSchemeRegistrationSession();
            List<Guid> selectedPrnIds = session.PrnSession.SelectedPrnIds;

            var viewModel = await _prnService.GetAllAcceptedPrnsAsync();
            var justUpdatedPrns = viewModel.Prns?.Where(x => selectedPrnIds.Contains(x.ExternalId)).ToList();

            string obligationYearsCsv = string.Empty;
            if (justUpdatedPrns != null)
            {
                obligationYearsCsv = string.Join(",", justUpdatedPrns.Select(x => x.ObligationYear).Distinct());
            }

            var summaryModel = new AcceptedPrnsModel()
            {
                NoteTypes = viewModel.GetNoteType(justUpdatedPrns),
                ObligationYears = obligationYearsCsv,
                Count = justUpdatedPrns.Count,
                Details = justUpdatedPrns
                            .GroupBy(x => x.Material)
                            .Select(x => new AcceptedDetails(x.Key, x.Sum(t => t.Tonnage)))
                            .ToList()
            };

            return View(summaryModel);
        }
    }
}

src/FrontendSchemeRegistration.UI/Views/PrnsAccept/AcceptMultiplePrns.cshtml
@using FrontendSchemeRegistration.Application.Constants
@using FrontendSchemeRegistration.UI.Controllers.Prns
@using FrontendSchemeRegistration.UI.ViewModels.Prns
@inject IStringLocalizer<PrnDataResources> PrnDataLocalizer
@model PrnListViewModel

@{
    ViewData["Title"] = Localizer["page_title"];
}

<main class="govuk-main-wrapper govuk-!-padding-top-4" id="main-content">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
            @if (Model.Prns.Any())
            {
                <fieldset class="govuk-fieldset">
                    <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                        <h1 class="govuk-label-wrapper">
                            <label class="govuk-label govuk-label--l" for="with-hint">@Localizer["review_your_selection"].Value</label>
                        </h1>
                    </legend>
                    <br>
                    <form class="form" method="POST">
                        @if (Model.RemovedPrn != null)
                        {
                            string removedPrnOrPern = Model.RemovedPrn.IsPrn ? "PRN" : "PERN";
                            <div class="govuk-notification-banner govuk-notification-banner--success" role="alert" aria-labelledby="govuk-notification-banner-title" data-module="govuk-notification-banner">
                                <div class="govuk-notification-banner__header">
                                    <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
                                        @SharedLocalizer["success"]
                                    </h2>
                                </div>
                                <div class="govuk-notification-banner__content">
                                    <h3 class="govuk-notification-banner__heading">
                                        @Localizer["you_have_removed_prn_number", removedPrnOrPern, Model.RemovedPrn.PrnNumber]
                                    </h3>
                                </div>
                            </div>
                        }

                       @{
                            int counter = 0;
                        }
                        @foreach (var group in Model.Prns.GroupBy(p => p.Material))
                        {
                            var prnsPerMaterial = group.ToList();
                            string h2HeaderText = @PrnDataLocalizer[group.Key].Value;
                            CountBreakdown subCounts = Model.GetCountBreakdown(prnsPerMaterial);
                            <table class="govuk-table">
                                <caption class="govuk-table__caption govuk-table__caption--m">
                                    <h2 class="govuk-heading-m">@h2HeaderText</h2>
                                </caption>
                                <thead class="govuk-table__head">
                                    <tr class="govuk-table__row">
                                        <th class="govuk-table__header">@Localizer[subCounts.ColumnHeaderLabel]</th>
                                        <th class="govuk-table__header">@Localizer["date_issued"]</th>
                                        <th class="govuk-table__header">@Localizer["issued_by"]</th>
                                        <th class="govuk-table__header">@Localizer["tonnage"]</th>
                                        <th class="govuk-table__header">@Localizer[subCounts.RemoveLinkText]</th>
                                    </tr>
                                </thead>

                                <tbody class="govuk-table__body">
                                    @for (int i = 0; i < prnsPerMaterial.Count; i++, counter++)
                                    {
                                        @Html.HiddenFor(x => x.Prns[counter].ExternalId)
                                        <tr class="govuk-table__row">
                                            <td class="govuk-table__header">@Html.DisplayFor(x => prnsPerMaterial[i].PrnOrPernNumber)</td>
                                            <td class="govuk-table__cell">@Html.DisplayFor(x => prnsPerMaterial[i].DateIssuedDisplay)</td>
                                            <td class="govuk-table__cell">@Html.DisplayFor(x => prnsPerMaterial[i].IssuedBy)</td>
                                            <td class="govuk-table__cell govuk-table__cell--numeric">@Html.DisplayFor(x => prnsPerMaterial[i].Tonnage)</td>
                                            <td class="govuk-table__cell">
                                                <label class="govuk-label govuk-checkboxes__label">
                                                    <a href="?id=@prnsPerMaterial[i].ExternalId" class="href-text--red">
                                                        @Localizer["remove_from_selection"]
                                                    </a>
                                                </label>
                                            </td>
                                        </tr>
                                    }
                                    <tr class="govuk-table__row">
                                        <td class="govuk-table__header">@SharedLocalizer["total"]</td>
                                        <td class="govuk-table__cell"></td>
                                        <td class="govuk-table__cell"></td>
                                        <td class="govuk-table__cell govuk-table__cell--numeric"><strong>@prnsPerMaterial.Sum(x => x.Tonnage)</strong></td>
                                        <td class="govuk-table__cell"></td>
                                    </tr>
                                </tbody>
                            </table>
                            <br>
                            <br>
                        }
                        <h2 class="govuk-heading-l">@Localizer["now_accept"]</h2>
                        <p class="govuk-body govuk-\!-margin-bottom-static-4"> @Localizer["accepting_them_will_credit_the_tonnage_towards_your_obligation"]</p>
                        <br/>
                        <div class="govuk-button-group govuk-\!-margin-top-8">
                            <button class="govuk-button" type="submit" asp-action=@nameof(PrnsAcceptController.ConfirmAcceptMultiplePrnsPassThrough) asp-controller="PrnsAccept">
                                @Localizer["accept"]
                            </button>
                        </div>
                    </form>
                </fieldset>
            }
            else
            {
                ViewBag.BackLinkToDisplay = Url?.Content(PagePaths.Prns.ShowAwaitingAcceptance);
                string noteTypes = ViewBag.StartNoteTypes;

                var noteTypesLocalised = noteTypes == PrnConstants.PrnsAndPernsText ?
                    string.Format(Localizer["you_have_remove_all_mix_selected_notes"].Value, PrnDataLocalizer[PrnConstants.PrnsText], PrnDataLocalizer[PrnConstants.PernsText]) :
                    string.Format(Localizer["you_have_remove_only_selected_notes"].Value, PrnDataLocalizer[noteTypes]);

                <h1 class="govuk-heading-l">@noteTypesLocalised</h1>

                @Html.ActionLink(Localizer["accept_or_reject_prns_perns"].Value, nameof(PrnsController.SelectMultiplePrns), "Prns", null,
                    new
                    {
                        @class = "govuk-button"
                    })
            }
        </div>
    </div>
</main>

src/FrontendSchemeRegistration.UI/Views/PrnsAccept/AcceptSinglePrn.cshtml
@using FrontendSchemeRegistration.UI.Controllers.Prns
@using FrontendSchemeRegistration.UI.ViewModels.Prns
@inject IStringLocalizer<PrnDataResources> PrnDataLocalizer
@model PrnViewModel

@{
    ViewData["Title"] = Localizer[(Model.IsPrn ? "prn_page_title" : "pern_page_title")];
    var headerText = string.Format(Localizer[(Model.IsPrn ? "prn_heading" : "pern_heading")].Value, Model.EffectiveAcceptanceYear);
}
<main class="govuk-main-wrapper govuk-!-padding-top-4" id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">

            <form class="form" method="POST">
                @Html.HiddenFor(model => model.ExternalId)
                <h2 class="govuk-heading-l">@headerText</h2>

                <div class="govuk-inset-text">                   
                    @string.Format(Localizer["Title"].Value, Model.Tonnage, @PrnDataLocalizer[Model.Material].Value)
                </div>

                <div class="govuk-button-group">
                    @if (Model.IsStatusEditable)
                    {
                        <button class="govuk-button" type="submit" asp-action=@nameof(PrnsAcceptController.ConfirmAcceptSinglePrnPassThrough) asp-controller="PrnsAccept">
                            @Localizer["YesAcceptButton"]
                        </button>
                    }

                    @Html.ActionLink(@Localizer["NoBackButton"].Value, nameof(PrnsController.SelectSinglePrn), "Prns",
                        new
                        {
                            id = @Model.ExternalId
                        },
                        new
                        {
                            @class = "govuk-button govuk-button--secondary"
                        })
                </div>
            </form>
        </div>
    </div>
</main>

src/FrontendSchemeRegistration.UI/Views/PrnsAccept/AcceptedPrn.cshtml
@using FrontendSchemeRegistration.UI.Controllers.Prns
@using FrontendSchemeRegistration.UI.ViewModels.Prns
@inject IStringLocalizer<PrnDataResources> PrnDataLocalizer
@model PrnViewModel

@{
    ViewData["Title"] = Localizer["page_title"];
    var isPdf = ViewData["IsPdf"] as bool? ?? false;
}

<main class="govuk-main-wrapper govuk-!-padding-top-4">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
            @await Html.PartialAsync("../Shared/Partials/Prns/_agenciesLogo.cshtml")
            @if(!isPdf)
            {
                <div class="govuk-notification-banner govuk-notification-banner--success" role="alert" aria-labelledby="govuk-notification-banner-title" data-module="govuk-notification-banner">
                    <div class="govuk-notification-banner__header">
                        <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
                            @SharedLocalizer["success"]
                        </h2>
                    </div>
                    <div class="govuk-notification-banner__content">
                        <h3 class="govuk-notification-banner__heading">
                            @string.Format(Localizer["prn_accepted"].Value, PrnDataLocalizer[Model.NoteType], Model.EffectiveAcceptanceYear)
                        </h3>
                        <p class="govuk-body">@Localizer["tonnage_credited_towards_your_obligation", Model.Tonnage, @PrnDataLocalizer[Model.Material].Value]</p>
                        <button id="downloadPDFButton" class="govuk-body govuk-link">
                            @string.Format(Localizer["download_this_prn"].Value, PrnDataLocalizer[Model.NoteType])
                        </button>
                    </div>
                </div>
            }
            <h1 class="govuk-heading-l">
                @Localizer[(Model.IsPrn ? "prn_note" : "pern_note")]
            </h1>
            <div class="govuk-inset-text app-inset-text">
                <div class="govuk-heading-m">
                    @string.Format(Localizer["prn_number"].Value, PrnDataLocalizer[Model.NoteType]): <strong>@Model.PrnOrPernNumber</strong>
                </div>
                <div class="govuk-heading-m">
                    @Localizer["year"]: <strong>@Model.IssueYear</strong>
                </div>
            </div>
            @await Html.PartialAsync("../Shared/Partials/Prns/_recyclingNoteStatus.cshtml", Model)
            <br>
            @await Html.PartialAsync("../Shared/Partials/Prns/_recyclingNoteDetails.cshtml", Model)
            @if (!isPdf)
            {
                <br>
                <br>
                <div class="govuk-button-group">
                    <form method="get" asp-action="HomePagePrn" asp-controller="Prns">
                        @Html.ActionLink(string.Format(Localizer["accept_or_reject_more_prns_and_perns"].Value, PrnDataLocalizer[PrnConstants.PrnsText], PrnDataLocalizer[PrnConstants.PernsText]),
                                 nameof(PrnsController.SelectMultiplePrns), "Prns", null,
                                 new
                                 {
                                     @class = "govuk-button"
                                 })
                        @Html.ActionLink(Localizer["manage_obligation_home"].Value, nameof(PrnsObligationController.ObligationsHome), "PrnsObligation",
                                 null,
                                 new
                                 {
                                     @class = "govuk-button govuk-button--secondary"
                                 })
                    </form>
                </div>
            }
        </div>
    </div>
</main>
@section Scripts {
    <script src="~/js/html2pdf-0.9.3.min.js"></script>
    <script src="~/js/download-pdf.js"></script>
}

src/FrontendSchemeRegistration.UI/Views/PrnsAccept/AcceptedPrns.cshtml
@using FrontendSchemeRegistration.UI.Controllers.Prns
@using FrontendSchemeRegistration.UI.ViewModels.Prns
@inject IStringLocalizer<PrnDataResources> PrnDataLocalizer
@model AcceptedPrnsModel
@{
    ViewData["Title"] = Localizer["page_title"];
    var summaryText = string.Empty;

    if (Model.NoteTypes == PrnConstants.PrnText || Model.NoteTypes == PrnConstants.PernText)
    {
        summaryText = string.Format(Localizer["you_have_accepted_one_prn_or_pern"].Value, PrnDataLocalizer[Model.NoteTypes]);
    }
    else if (Model.NoteTypes == PrnConstants.PrnsText || Model.NoteTypes == PrnConstants.PernsText)
    {
        summaryText = string.Format(Localizer["you_have_accepted_multipe_prn_or_pern"].Value, Model.Count, PrnDataLocalizer[Model.NoteTypes]);
    }
    else
    {
        var noteTypes = Model.NoteTypes.Split(",");
        summaryText = string.Format(Localizer["you_have_accepted_mix_prns_and_perns"].Value, Model.Count, PrnDataLocalizer[noteTypes[0]], PrnDataLocalizer[noteTypes[1]]);
    }
}

<main class="govuk-main-wrapper govuk-!-padding-top-4" aria-label="main" id="main-content" role="main">

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <main class="govuk-main-wrapper govuk-main-wrapper--l" aria-label="confirmation" id="main-content-confirmation" role="main">
                <div class="govuk-grid-row">
                    <div class="govuk-grid-column-full">
                        <div class="govuk-panel govuk-panel--confirmation">
                            <h1 class="govuk-panel__title">
                                @summaryText
                            </h1>
                        </div>
                    </div>
                </div>
            </main>

            <h2 class="govuk-heading-m">@Localizer["what_happens_next"]</h2>
            <p class="govuk-body">
                @Localizer[Model.Count == 1 ? "we_will_credit_this_towards_your_yyyy_recycling obligations" : "we_will_credit_these_towards_your_yyyy_recycling obligations", Model.ObligationYears]
            </p>
            @for (int i = 0; i < Model.Details.Count; i++)
            {
                <div class="govuk-grid-row">
                    <div class="govuk-grid-column-one-half">
                        <div class="card govuk-card--blue govuk-!-margin-bottom-5">
                            <div class="govuk-card-body">
                                <h2 class="govuk-heading-s govuk-!-margin-bottom-3 govuk-card-body-text--white">@PrnDataLocalizer[Model.Details[i].Material]</h2>
                                <h2 class="govuk-heading-xl govuk-!-margin-bottom-3 govuk-card-body-text--white">@Localizer["number_tonnes", Model.Details[i].Tonnage]</h2>
                                <p class="govuk-body govuk-!-margin-bottom-3 govuk-card-body-text--white">@Localizer["credited_towards_your_material_obligation", @PrnDataLocalizer[Model.Details[i].Material].Value]</p>
                            </div>
                        </div>
                    </div>
                    @if (i + 1 < Model.Details.Count)
                    {
                        i++;
                        <div class="govuk-grid-column-one-half">
                            <div class="card govuk-card--blue govuk-!-margin-bottom-5">
                                <div class="govuk-card-body">
                                    <h2 class="govuk-heading-s govuk-!-margin-bottom-3 govuk-card-body-text--white">@PrnDataLocalizer[Model.Details[i].Material]</h2>
                                    <h2 class="govuk-heading-xl govuk-!-margin-bottom-3 govuk-card-body-text--white">@Localizer["number_tonnes", Model.Details[i].Tonnage]</h2>
                                    <p class="govuk-body govuk-!-margin-bottom-3 govuk-card-body-text--white">@Localizer["credited_towards_your_material_obligation", @PrnDataLocalizer[Model.Details[i].Material].Value]</p>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }

            <p class="govuk-body">
                @Localizer["download_prns_and_perns_from_search_page_part_1"]
                <a href="view-awaiting-acceptance" class="govuk-link">@Localizer["download_prns_and_perns_from_search_page_part_2"]</a>
                @Localizer["download_prns_and_perns_from_search_page_part_3"]
            </p>
            
            <div class="govuk-button-group">

                @Html.ActionLink(Localizer["view_recycling_obligations_progress"].Value, nameof(PrnsObligationController.ObligationsHome), "PrnsObligation",
                         null,
                         new
                         {
                             @class = "govuk-button govuk-button--primary"
                         })
            </div>

        </div>
    </div>
</main>